name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x, 16.x, 18.x]
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, debian-10, debian-12, macos-latest, windows-latest, windows-2016, windows-2019, windows-2022]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

  # Add separate jobs for specific OS versions if needed

  linux-ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 8.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  linux-ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 8.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  linux-ubuntu-24-04:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 8.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  linux-debian-10:
    runs-on: debian-10
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 8.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  linux-debian-12:
    runs-on: debian-12
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 8.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  macos-latest:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 8.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  windows-latest:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 8.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  windows-2016:
    runs-on: windows-2016
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 8.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  windows-2019:
    runs-on: windows-2019
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 8.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  windows-2022:
    runs-on: windows-2022
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 8.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
